function mbfdtd1d_publication_style(ax)
%MBFDTD1D_PUBLICATION_STYLE Shared figure styling.

if nargin < 1 || isempty(ax)
    ax = gca;
end

set(ax, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11, ...
    'LineWidth', 1.0, ...
    'Box', 'on', ...
    'TickDir', 'out', ...
    'Layer', 'top');

fig = ancestor(ax, 'figure');
set(fig, 'Color', 'w');
end
